// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAavHZ32tQjzETMcBki_YSy7sLALhVq2s',
    appId: '1:320731247095:web:20c249f781ed8c29b17ef2',
    messagingSenderId: '320731247095',
    projectId: 'iskambil-84d16',
    authDomain: 'iskambil-84d16.firebaseapp.com',
    databaseURL: 'https://iskambil-84d16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iskambil-84d16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWAZj4whRvpdmu3rtiH3p1Mtd6mIVvgEQ',
    appId: '1:320731247095:android:d15c083f6d30c414b17ef2',
    messagingSenderId: '320731247095',
    projectId: 'iskambil-84d16',
    databaseURL: 'https://iskambil-84d16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iskambil-84d16.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHizoZsHcGaQCwRZpm8EtJAY8s1Kfvork',
    appId: '1:320731247095:ios:0d2356bbd7a4345ab17ef2',
    messagingSenderId: '320731247095',
    projectId: 'iskambil-84d16',
    databaseURL: 'https://iskambil-84d16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iskambil-84d16.firebasestorage.app',
    androidClientId: '320731247095-7toj5sl9b0nm1g4anuhl6g2lg4mcsu7v.apps.googleusercontent.com',
    iosClientId: '320731247095-tnfdd9h5q8vu5pgm153biq0nr8cugcju.apps.googleusercontent.com',
    iosBundleId: 'com.example.kartOyunu',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHizoZsHcGaQCwRZpm8EtJAY8s1Kfvork',
    appId: '1:320731247095:ios:0d2356bbd7a4345ab17ef2',
    messagingSenderId: '320731247095',
    projectId: 'iskambil-84d16',
    databaseURL: 'https://iskambil-84d16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iskambil-84d16.firebasestorage.app',
    androidClientId: '320731247095-7toj5sl9b0nm1g4anuhl6g2lg4mcsu7v.apps.googleusercontent.com',
    iosClientId: '320731247095-tnfdd9h5q8vu5pgm153biq0nr8cugcju.apps.googleusercontent.com',
    iosBundleId: 'com.example.kartOyunu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAavHZ32tQjzETMcBki_YSy7sLALhVq2s',
    appId: '1:320731247095:web:e0e096725d13857ab17ef2',
    messagingSenderId: '320731247095',
    projectId: 'iskambil-84d16',
    authDomain: 'iskambil-84d16.firebaseapp.com',
    databaseURL: 'https://iskambil-84d16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iskambil-84d16.firebasestorage.app',
  );
}
